server:
  port: 10010
spring:
  application:
    name: lee-zuul
zuul:
  routes:
    service-provider: /user/** #路由的名称，可以随便写，习惯上写服务名
      #path: /service-provider/**   # 路由的路径
      #url: http://localhost:8081   # 暴露服务地址
      #serviceId: service-provider   # 配置服务名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka