server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///ssm_pages
    username: root
    password: root
  application:
    name: service-provider  # 将来会作为微服务的名称
mybatis:
  type-aliases-package: cn.lee.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true  # 服务提供方启动时，会检测该参数是否为true，true-注册给eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 # 过期时间